TP3: 
	mpicc -o ../obj/mpiflood ../src/mpiflood.c
clean: 
	rm ../obj/*
	
copy:	
	if test -d /home/sod/2010/tp3/Zenobi-DIorio-Rossanigo; then echo "el path ya existe"; else mkdir /home/sod/2010/tp3/Zenobi-DIorio-Rossanigo; fi
	cp -R -f -u ../* /home/sod/2010/tp3/Zenobi-DIorio-Rossanigo
	
