TP1: 
	gcc -o ../obj/tcpping ../src/ClienteTcp.c
	gcc -o ../obj/tcppingd ../src/ServidorTcp.c
	gcc -o ../obj/udppingd ../src/ServidorUdp.c
	gcc -o ../obj/udpping ../src/ClienteUdp.c
	
clean: 
	rm ../obj/*
	
	
